# Generated by Django 4.2.6 on 2024-03-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist_app', '0001_initial'),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pay_number', models.CharField(max_length=100)),
                ('Admit_date', models.DateField(max_length=100)),
                ('Lab_payment', models.TextField(max_length=200, null=True)),
                ('Food_payment', models.TextField(max_length=100, null=True)),
                ('Service_payment', models.TextField(max_length=100, null=True)),
                ('Card_payment', models.TextField(max_length=100)),
                ('Bed_payment', models.TextField(max_length=100, null=True)),
                ('Pay_method', models.TextField(max_length=100, null=True)),
                ('Total', models.TextField(max_length=100, null=True)),
                ('Casher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casher_send_set', related_query_name='casher_send_set', to='admin_app.userprofileinfo2')),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patientregister')),
            ],
        ),
    ]
