# Generated by Django 5.0.2 on 2024-03-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casher_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='Total',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
