# Generated by Django 5.0.2 on 2024-03-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casher_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_payment', models.TextField(max_length=100)),
                ('Service_payment', models.TextField(max_length=100)),
                ('Card_payment', models.TextField(max_length=100)),
                ('Bed_payment', models.TextField(max_length=100)),
            ],
        ),
    ]
