# Generated by Django 5.0.2 on 2024-03-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casher_app', '0003_alter_paymentmodel_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='Total',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
    ]
