# Generated by Django 5.0.2 on 2024-03-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casher_app', '0003_servicepayment_lab_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepayment',
            old_name='Bed_payment',
            new_name='Payment',
        ),
        migrations.RenameField(
            model_name='servicepayment',
            old_name='Card_payment',
            new_name='Services',
        ),
        migrations.RemoveField(
            model_name='servicepayment',
            name='Food_payment',
        ),
        migrations.RemoveField(
            model_name='servicepayment',
            name='Lab_payment',
        ),
        migrations.RemoveField(
            model_name='servicepayment',
            name='Service_payment',
        ),
    ]
