# Generated by Django 5.0.2 on 2024-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casher_app', '0004_alter_paymentmodel_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='Bed_payment',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='Card_payment',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='Food_payment',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='Lab_payment',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='Service_payment',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
    ]
