# Generated by Django 5.0.2 on 2024-03-22 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casher_app', '0005_servicepayment_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='Casher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casher_send_set', related_query_name='casher_send_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
