# Generated by Django 5.0.2 on 2024-04-19 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casher_app', '0005_alter_paymentmodel_bed_payment_and_more'),
        ('receptionist_app', '0002_patientregister_symptom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('Discharge_no', models.AutoField(primary_key=True, serialize=False)),
                ('Reason', models.TextField(max_length=100, null=True)),
                ('Departure_date', models.DateField(null=True)),
                ('Status', models.TextField(max_length=100, null=True)),
                ('No_days', models.BigIntegerField(null=True)),
                ('Reffer_to', models.TextField(max_length=100, null=True)),
                ('Approval', models.BooleanField(default=False)),
                ('Casher_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patientregister')),
            ],
        ),
    ]
