# Generated by Django 5.0 on 2024-01-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=255)),
                ('test_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
