# Generated by Django 5.0.2 on 2024-03-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo2',
            old_name='profession',
            new_name='specialty',
        ),
        migrations.AddField(
            model_name='userprofileinfo2',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
