# Generated by Django 5.0.2 on 2024-05-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_no', models.DateTimeField(auto_created=True)),
                ('Name', models.TextField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Feedback', models.TextField(max_length=500)),
            ],
        ),
    ]
