# Generated by Django 5.0 on 2024-01-04 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.labtest')),
            ],
        ),
    ]
