# Generated by Django 5.0.2 on 2024-02-24 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('alloc_date', models.DateField(default=django.utils.timezone.now)),
                ('departure_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
