# Generated by Django 5.0.2 on 2024-05-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
