# Generated by Django 5.0.2 on 2024-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_userprofileinfo2_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo2',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics'),
        ),
    ]
