# Generated by Django 5.0.2 on 2024-03-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_userprofileinfo2_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='lab_test',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
