# Generated by Django 5.0.2 on 2024-02-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount1',
            fields=[
                ('UserName', models.CharField(primary_key=True, serialize=False)),
                ('Profession', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Profile', models.ImageField(blank=True, upload_to='profile')),
            ],
        ),
    ]
