# Generated by Django 5.0.2 on 2024-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_feedback_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Added_no',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
