# Generated by Django 5.0.2 on 2024-05-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_feedback_added_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('Name', models.TextField(max_length=100, null=True)),
                ('Title', models.TextField(max_length=100, null=True)),
                ('Report_file', models.FileField(blank=True, upload_to='documents/')),
                ('Added_no', models.DateTimeField(auto_now_add=True)),
                ('Report_no', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
