# Generated by Django 5.0.2 on 2024-05-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100)),
                ('Message', models.TextField(max_length=500)),
                ('Title', models.TextField(max_length=100)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100)),
                ('Message', models.TextField(max_length=500)),
                ('Title', models.TextField(max_length=100)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Seen', models.BooleanField(default=False)),
            ],
        ),
    ]
