# Generated by Django 4.2.6 on 2024-02-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Sympthom', models.CharField(max_length=100)),
                ('DiseaseName', models.CharField(max_length=100)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_history_set', related_query_name='doctor_history', to='admin_app.useraccount1')),
                ('Nurse_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_history_set', related_query_name='doctor_history', to='admin_app.useraccount1')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.patient')),
            ],
        ),
    ]
