# Generated by Django 5.0.2 on 2024-02-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_patienthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='PatientID',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='Doctor_ID',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='Nurse_ID',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientHistory',
        ),
        migrations.DeleteModel(
            name='UserAccount1',
        ),
    ]
