# Generated by Django 5.0.2 on 2024-02-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_remove_patienthistory_patientid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo2',
            name='protfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo2',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
