# Generated by Django 5.0.2 on 2024-02-19 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0008_remove_patienthistory_patientid_and_more'),
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Sympthom', models.CharField(max_length=100)),
                ('DiseaseName', models.CharField(max_length=100)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_history_set', related_query_name='doctor_history', to='admin_app.userprofileinfo2')),
                ('Nurse_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.userprofileinfo2')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patient')),
            ],
        ),
    ]
