# Generated by Django 5.0.2 on 2024-03-29 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_number', models.CharField(max_length=100)),
                ('App_date', models.DateField(max_length=100)),
                ('Time_slot', models.TextField(max_length=100)),
                ('App_reseon', models.TextField(max_length=200)),
                ('App_status', models.TextField(max_length=100)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patientregister')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lab_number', models.CharField(max_length=100)),
                ('Admit_date', models.DateField(max_length=100)),
                ('Lab_type', models.TextField(max_length=200)),
                ('Lab_result', models.TextField(max_length=100, null=True)),
                ('Is_tested', models.BooleanField(default=False)),
                ('Is_payed', models.BooleanField(default=False)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patientregister')),
                ('Technician_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_send_set', related_query_name='laboratory_send_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('Date', models.DateField()),
                ('Sympthom', models.CharField(max_length=100)),
                ('History_No', models.AutoField(primary_key=True, serialize=False)),
                ('DiseaseName', models.CharField(max_length=100)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_history_set', related_query_name='doctor_history', to=settings.AUTH_USER_MODEL)),
                ('Nurse_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patientregister')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prec_number', models.CharField(max_length=100)),
                ('Prec_date', models.DateField(max_length=100)),
                ('Precscriptions', models.TextField(max_length=200, null=True)),
                ('Patient_full_name', models.TextField(max_length=100)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patientregister')),
            ],
        ),
    ]
