# Generated by Django 5.0.2 on 2024-03-01 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        ('doctor_app', '0001_initial'),
        ('receptionist_app', '0002_patientregister_is_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lab_number', models.CharField(max_length=100)),
                ('Admit_date', models.DateField(max_length=100)),
                ('Lab_type', models.TextField(max_length=200)),
                ('Lab_result', models.TextField(max_length=100)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.userprofileinfo2')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patientregister')),
                ('Technician_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_send_set', related_query_name='laboratory_send_set', to='admin_app.userprofileinfo2')),
            ],
        ),
    ]
