# Generated by Django 5.0.2 on 2024-02-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='P_ID',
            new_name='PatientID',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='P_ID',
            new_name='PatientID',
        ),
    ]
