# Generated by Django 5.0.2 on 2024-02-20 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_remove_patienthistory_patientid_and_more'),
        ('doctor_app', '0001_initial'),
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_Number', models.CharField()),
                ('App_date', models.DateField(max_length=100)),
                ('Time_slot', models.TimeField(max_length=100)),
                ('App_reseon', models.TextField(max_length=200)),
                ('App_status', models.TextField(max_length=100)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.userprofileinfo2')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patient')),
            ],
        ),
    ]
