# Generated by Django 5.0.2 on 2024-05-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='Is_prescriped',
            field=models.BooleanField(default=False),
        ),
    ]
