# Generated by Django 5.0.2 on 2024-02-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='App_Number',
            new_name='App_number',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='PatientID',
            new_name='Patient_ID',
        ),
    ]
