# Generated by Django 5.0.2 on 2024-02-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_rename_p_id_appointment_patientid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthistory',
            old_name='PatientID',
            new_name='Patient_ID',
        ),
    ]
