# Generated by Django 5.0.2 on 2024-04-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_patienthistory_symptom2'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='Is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
