# Generated by Django 5.0.2 on 2024-05-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_laboratory_is_prescriped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Time_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Appointment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='End_Time',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Start_Time',
            field=models.TimeField(max_length=100, null=True),
        ),
    ]
