# Generated by Django 5.0.2 on 2024-02-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0003_rename_app_number_appointment_app_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Patient_ID',
            new_name='P_ID',
        ),
    ]
