# Generated by Django 5.0.2 on 2024-03-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0003_alter_laboratory_lab_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='Is_tested',
            field=models.BooleanField(default=False),
        ),
    ]
