# Generated by Django 5.0.2 on 2024-02-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0004_rename_patient_id_appointment_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Time_slot',
            field=models.TextField(max_length=100),
        ),
    ]
