# Generated by Django 5.0.2 on 2024-02-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0006_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='Precscriptions',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
