# Generated by Django 5.0.2 on 2024-02-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInformation',
            fields=[
                ('Room_block', models.TextField(max_length=100)),
                ('Room_no', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('Bed_no', models.CharField(max_length=100)),
                ('Status', models.TextField(max_length=100)),
            ],
        ),
    ]
