# Generated by Django 5.0.2 on 2024-03-29 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInformation',
            fields=[
                ('Room_block', models.TextField(max_length=100)),
                ('Room_no', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('Bed_no', models.CharField(max_length=100)),
                ('Status', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VitalInformation',
            fields=[
                ('Vital_info_no', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('H_rate', models.CharField(max_length=100)),
                ('B_pressure', models.TextField(max_length=100)),
                ('Body_temp', models.TextField(max_length=100)),
                ('Pain_level', models.TextField(max_length=100)),
                ('Weight', models.TextField(max_length=100)),
                ('Height', models.TextField(max_length=100)),
                ('Oxy_satu', models.TextField(max_length=100)),
                ('B_gluc_level', models.TextField(max_length=100)),
                ('R_rate', models.TextField(max_length=100)),
                ('D_record', models.DateField()),
                ('Remark', models.TextField(max_length=100)),
                ('Nurse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_vitalinfo_set', related_query_name='nurse_vitalinfo_set', to='receptionist_app.patientregister')),
            ],
        ),
    ]
