# Generated by Django 5.0.2 on 2024-05-09 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInformation',
            fields=[
                ('Room_block', models.TextField(max_length=100)),
                ('Room_no', models.TextField()),
                ('Bed_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Room_type', models.CharField(max_length=100)),
                ('Status', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('Med_time', models.TimeField(auto_now_add=True)),
                ('Bed_no', models.BigIntegerField()),
                ('Remark', models.TextField(max_length=100)),
                ('Drugs', models.TextField(max_length=100)),
                ('Med_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nurse_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patientregister')),
            ],
        ),
        migrations.CreateModel(
            name='BedInformation',
            fields=[
                ('Room_num', models.TextField()),
                ('Room_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Room_type', models.CharField(max_length=100)),
                ('Alloc_date', models.DateField(auto_now_add=True)),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patientregister')),
                ('Bed_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_app.roominformation')),
            ],
        ),
        migrations.CreateModel(
            name='VitalInformation',
            fields=[
                ('Vital_info_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('H_rate', models.CharField(max_length=100)),
                ('B_pressure', models.TextField(max_length=100)),
                ('Body_temp', models.TextField(max_length=100)),
                ('Pain_level', models.TextField(max_length=100)),
                ('Weight', models.TextField(max_length=100)),
                ('Height', models.TextField(max_length=100)),
                ('Oxy_satu', models.TextField(max_length=100)),
                ('B_gluc_level', models.TextField(max_length=100)),
                ('R_rate', models.TextField(max_length=100)),
                ('D_record', models.DateField(auto_now_add=True)),
                ('Remark', models.TextField(max_length=100)),
                ('Nurse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_vitalinfo_set', related_query_name='nurse_vitalinfo_set', to='receptionist_app.patientregister')),
            ],
        ),
    ]
