# Generated by Django 5.0.2 on 2024-02-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominformation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1111, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='Room_no',
            field=models.TextField(max_length=100),
        ),
    ]
