# Generated by Django 5.0.2 on 2024-04-03 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0001_initial'),
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Med_time', models.TextField(max_length=100)),
                ('Bed_no', models.CharField(max_length=100)),
                ('Remark', models.TextField(max_length=100)),
                ('Nurse_name', models.TextField(max_length=100)),
                ('Drugs', models.TextField(max_length=100)),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patientregister')),
            ],
        ),
    ]
