# Generated by Django 5.0.2 on 2024-02-25 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        ('nurse_app', '0001_initial'),
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalInformation',
            fields=[
                ('Vital_info_no', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('H_rate', models.CharField(max_length=100)),
                ('B_pressure', models.TextField(max_length=100)),
                ('Body_temp', models.TextField(max_length=100)),
                ('Pain_level', models.TextField(max_length=100)),
                ('Weight', models.TextField(max_length=100)),
                ('Height', models.TextField(max_length=100)),
                ('Oxy_satu', models.TextField(max_length=100)),
                ('B_gluc_level', models.TextField(max_length=100)),
                ('R_rate', models.TextField(max_length=100)),
                ('D_record', models.DateField()),
                ('Remark', models.TextField(max_length=100)),
                ('Nurse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.userprofileinfo2')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patientregister')),
            ],
        ),
    ]
