# Generated by Django 5.0.2 on 2024-02-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0002_roominformation_id_alter_roominformation_room_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='Room_no',
            field=models.TextField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
