# Generated by Django 5.0.2 on 2024-02-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0002_vitalinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitalinformation',
            old_name='PatientID',
            new_name='Patient_ID',
        ),
    ]
