# Generated by Django 5.0.2 on 2024-04-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0002_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='id',
        ),
        migrations.AddField(
            model_name='medication',
            name='Med_no',
            field=models.TextField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
