# Generated by Django 5.0.2 on 2024-04-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0003_remove_medication_id_medication_med_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='Med_no',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
