# Generated by Django 5.0.2 on 2024-02-26 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0004_rename_patient_id_vitalinformation_patient_id'),
        ('receptionist_app', '0002_alter_patientregister_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalinformation',
            name='Patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_vitalinfo_set', related_query_name='nurse_vitalinfo_set', to='receptionist_app.patientregister'),
        ),
    ]
