# Generated by Django 5.0.2 on 2024-04-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0005_alter_medication_nurse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='Med_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
