# Generated by Django 5.0.2 on 2024-04-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0006_alter_medication_med_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominformation',
            name='Room_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
