# Generated by Django 5.0.2 on 2024-04-10 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0007_roominformation_room_type'),
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bed_no', models.CharField(max_length=100)),
                ('Room_type', models.CharField(max_length=100, null=True)),
                ('Alloc_date', models.DateField(max_length=100)),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patientregister')),
                ('Room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_app.roominformation')),
            ],
        ),
    ]
