INSERT INTO "auth_permission" VALUES ('1','Can add log entry','1','add_logentry');
INSERT INTO "auth_permission" VALUES ('2','Can change log entry','1','change_logentry');
INSERT INTO "auth_permission" VALUES ('3','Can delete log entry','1','delete_logentry');
INSERT INTO "auth_permission" VALUES ('4','Can view log entry','1','view_logentry');
INSERT INTO "auth_permission" VALUES ('5','Can add permission','2','add_permission');
INSERT INTO "auth_permission" VALUES ('6','Can change permission','2','change_permission');
INSERT INTO "auth_permission" VALUES ('7','Can delete permission','2','delete_permission');
INSERT INTO "auth_permission" VALUES ('8','Can view permission','2','view_permission');
INSERT INTO "auth_permission" VALUES ('9','Can add group','3','add_group');
INSERT INTO "auth_permission" VALUES ('10','Can change group','3','change_group');
INSERT INTO "auth_permission" VALUES ('11','Can delete group','3','delete_group');
INSERT INTO "auth_permission" VALUES ('12','Can view group','3','view_group');
INSERT INTO "auth_permission" VALUES ('13','Can add user','4','add_user');
INSERT INTO "auth_permission" VALUES ('14','Can change user','4','change_user');
INSERT INTO "auth_permission" VALUES ('15','Can delete user','4','delete_user');
INSERT INTO "auth_permission" VALUES ('16','Can view user','4','view_user');
INSERT INTO "auth_permission" VALUES ('17','Can add content type','5','add_contenttype');
INSERT INTO "auth_permission" VALUES ('18','Can change content type','5','change_contenttype');
INSERT INTO "auth_permission" VALUES ('19','Can delete content type','5','delete_contenttype');
INSERT INTO "auth_permission" VALUES ('20','Can view content type','5','view_contenttype');
INSERT INTO "auth_permission" VALUES ('21','Can add session','6','add_session');
INSERT INTO "auth_permission" VALUES ('22','Can change session','6','change_session');
INSERT INTO "auth_permission" VALUES ('23','Can delete session','6','delete_session');
INSERT INTO "auth_permission" VALUES ('24','Can view session','6','view_session');
INSERT INTO "auth_permission" VALUES ('25','Can add notification','7','add_notification');
INSERT INTO "auth_permission" VALUES ('26','Can change notification','7','change_notification');
INSERT INTO "auth_permission" VALUES ('27','Can delete notification','7','delete_notification');
INSERT INTO "auth_permission" VALUES ('28','Can view notification','7','view_notification');
INSERT INTO "auth_permission" VALUES ('29','Can add user','8','add_userprofile');
INSERT INTO "auth_permission" VALUES ('30','Can change user','8','change_userprofile');
INSERT INTO "auth_permission" VALUES ('31','Can delete user','8','delete_userprofile');
INSERT INTO "auth_permission" VALUES ('32','Can view user','8','view_userprofile');
INSERT INTO "auth_permission" VALUES ('33','Can add user profile info','9','add_userprofileinfo');
INSERT INTO "auth_permission" VALUES ('34','Can change user profile info','9','change_userprofileinfo');
INSERT INTO "auth_permission" VALUES ('35','Can delete user profile info','9','delete_userprofileinfo');
INSERT INTO "auth_permission" VALUES ('36','Can view user profile info','9','view_userprofileinfo');
INSERT INTO "auth_permission" VALUES ('37','Can add room information','10','add_roominformation');
INSERT INTO "auth_permission" VALUES ('38','Can change room information','10','change_roominformation');
INSERT INTO "auth_permission" VALUES ('39','Can delete room information','10','delete_roominformation');
INSERT INTO "auth_permission" VALUES ('40','Can view room information','10','view_roominformation');
INSERT INTO "auth_permission" VALUES ('41','Can add medication','11','add_medication');
INSERT INTO "auth_permission" VALUES ('42','Can change medication','11','change_medication');
INSERT INTO "auth_permission" VALUES ('43','Can delete medication','11','delete_medication');
INSERT INTO "auth_permission" VALUES ('44','Can view medication','11','view_medication');
INSERT INTO "auth_permission" VALUES ('45','Can add bed information','12','add_bedinformation');
INSERT INTO "auth_permission" VALUES ('46','Can change bed information','12','change_bedinformation');
INSERT INTO "auth_permission" VALUES ('47','Can delete bed information','12','delete_bedinformation');
INSERT INTO "auth_permission" VALUES ('48','Can view bed information','12','view_bedinformation');
INSERT INTO "auth_permission" VALUES ('49','Can add vital information','13','add_vitalinformation');
INSERT INTO "auth_permission" VALUES ('50','Can change vital information','13','change_vitalinformation');
INSERT INTO "auth_permission" VALUES ('51','Can delete vital information','13','delete_vitalinformation');
INSERT INTO "auth_permission" VALUES ('52','Can view vital information','13','view_vitalinformation');
INSERT INTO "auth_permission" VALUES ('53','Can add appointment','14','add_appointment');
INSERT INTO "auth_permission" VALUES ('54','Can change appointment','14','change_appointment');
INSERT INTO "auth_permission" VALUES ('55','Can delete appointment','14','delete_appointment');
INSERT INTO "auth_permission" VALUES ('56','Can view appointment','14','view_appointment');
INSERT INTO "auth_permission" VALUES ('57','Can add laboratory','15','add_laboratory');
INSERT INTO "auth_permission" VALUES ('58','Can change laboratory','15','change_laboratory');
INSERT INTO "auth_permission" VALUES ('59','Can delete laboratory','15','delete_laboratory');
INSERT INTO "auth_permission" VALUES ('60','Can view laboratory','15','view_laboratory');
INSERT INTO "auth_permission" VALUES ('61','Can add patient history','16','add_patienthistory');
INSERT INTO "auth_permission" VALUES ('62','Can change patient history','16','change_patienthistory');
INSERT INTO "auth_permission" VALUES ('63','Can delete patient history','16','delete_patienthistory');
INSERT INTO "auth_permission" VALUES ('64','Can view patient history','16','view_patienthistory');
INSERT INTO "auth_permission" VALUES ('65','Can add prescription','17','add_prescription');
INSERT INTO "auth_permission" VALUES ('66','Can change prescription','17','change_prescription');
INSERT INTO "auth_permission" VALUES ('67','Can delete prescription','17','delete_prescription');
INSERT INTO "auth_permission" VALUES ('68','Can view prescription','17','view_prescription');
INSERT INTO "auth_permission" VALUES ('69','Can add service payment','18','add_servicepayment');
INSERT INTO "auth_permission" VALUES ('70','Can change service payment','18','change_servicepayment');
INSERT INTO "auth_permission" VALUES ('71','Can delete service payment','18','delete_servicepayment');
INSERT INTO "auth_permission" VALUES ('72','Can view service payment','18','view_servicepayment');
INSERT INTO "auth_permission" VALUES ('73','Can add discharge','19','add_discharge');
INSERT INTO "auth_permission" VALUES ('74','Can change discharge','19','change_discharge');
INSERT INTO "auth_permission" VALUES ('75','Can delete discharge','19','delete_discharge');
INSERT INTO "auth_permission" VALUES ('76','Can view discharge','19','view_discharge');
INSERT INTO "auth_permission" VALUES ('77','Can add payment model','20','add_paymentmodel');
INSERT INTO "auth_permission" VALUES ('78','Can change payment model','20','change_paymentmodel');
INSERT INTO "auth_permission" VALUES ('79','Can delete payment model','20','delete_paymentmodel');
INSERT INTO "auth_permission" VALUES ('80','Can view payment model','20','view_paymentmodel');
INSERT INTO "auth_permission" VALUES ('81','Can add patient register','21','add_patientregister');
INSERT INTO "auth_permission" VALUES ('82','Can change patient register','21','change_patientregister');
INSERT INTO "auth_permission" VALUES ('83','Can delete patient register','21','delete_patientregister');
INSERT INTO "auth_permission" VALUES ('84','Can view patient register','21','view_patientregister');
INSERT INTO "auth_permission" VALUES ('85','Can add feedback','22','add_feedback');
INSERT INTO "auth_permission" VALUES ('86','Can change feedback','22','change_feedback');
INSERT INTO "auth_permission" VALUES ('87','Can delete feedback','22','delete_feedback');
INSERT INTO "auth_permission" VALUES ('88','Can view feedback','22','view_feedback');
INSERT INTO "auth_permission" VALUES ('89','Can add report','23','add_report');
INSERT INTO "auth_permission" VALUES ('90','Can change report','23','change_report');
INSERT INTO "auth_permission" VALUES ('91','Can delete report','23','delete_report');
INSERT INTO "auth_permission" VALUES ('92','Can view report','23','view_report');
INSERT INTO "auth_permission" VALUES ('93','Can add bed allocation','24','add_bedallocation');
INSERT INTO "auth_permission" VALUES ('94','Can change bed allocation','24','change_bedallocation');
INSERT INTO "auth_permission" VALUES ('95','Can delete bed allocation','24','delete_bedallocation');
INSERT INTO "auth_permission" VALUES ('96','Can view bed allocation','24','view_bedallocation');
INSERT INTO "auth_permission" VALUES ('97','Can add rooms','25','add_rooms');
INSERT INTO "auth_permission" VALUES ('98','Can change rooms','25','change_rooms');
INSERT INTO "auth_permission" VALUES ('99','Can delete rooms','25','delete_rooms');
INSERT INTO "auth_permission" VALUES ('100','Can view rooms','25','view_rooms');
INSERT INTO "auth_permission" VALUES ('101','Can add user notification','26','add_usernotification');
INSERT INTO "auth_permission" VALUES ('102','Can change user notification','26','change_usernotification');
INSERT INTO "auth_permission" VALUES ('103','Can delete user notification','26','delete_usernotification');
INSERT INTO "auth_permission" VALUES ('104','Can view user notification','26','view_usernotification');
