# Generated by Django 5.0.3 on 2024-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregister',
            name='age',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
