# Generated by Django 5.0.2 on 2024-02-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregister',
            name='staff',
            field=models.CharField(max_length=200),
        ),
    ]
