# Generated by Django 5.0.2 on 2024-04-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_app', '0002_patientregister_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregister',
            name='is_card',
            field=models.BooleanField(default=False),
        ),
    ]
